development:
  adapter: postgresql
  database: abacus_app_development
  host: localhost

test:
    adapter: postgresql
    database: abacus_app_test
    host: localhost

production:
    adapter: postgresql
    database: abacus_app_production
    host: localhost