development:
  adapter: postgresql
  database: abacus_development
  host: localhost
  pool: 5
  username: postgres

test:
  adapter: postgresql
  database: abacus_test
  username: postgres
  pool: 5
  host: localhost

production:
  adapter: postgresql
  database: abacus_production
  host: localhost